# Generated by Django 5.2.3 on 2025-06-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_staffbase_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_avatar', to='employees.staffbase'),
        ),
    ]
