# Generated by Django 5.2.3 on 2025-06-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_manager_avatar_intern_interndetails_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
    ]
