# Generated by Django 5.2.3 on 2025-06-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_manager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intern',
            options={},
        ),
    ]
